name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'README.md'

jobs:
  build:
    name: 'Build and test'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          cache: maven
      - name: Build and test
        run: mvn clean install
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: surefire-reports
          path: '**/surefire-reports/*.txt'
        

